// <auto-generated />
namespace BandDrop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changingdatetimetosystemdatetime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changingdatetimetosystemdatetime));
        
        string IMigrationMetadata.Id
        {
            get { return "201808171409149_changing datetime to system datetime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
