// <auto-generated />
namespace BandDrop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingstringuseridforlinkingaccoutns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingstringuseridforlinkingaccoutns));
        
        string IMigrationMetadata.Id
        {
            get { return "201808150030162_adding string userid for linking accoutns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
