// <auto-generated />
namespace BandDrop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class allowingfornullfkfrommusiciantoband : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(allowingfornullfkfrommusiciantoband));
        
        string IMigrationMetadata.Id
        {
            get { return "201808150035299_allowing for null fk from musician to band"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
